### ISSUE TITLE
'/' method page returns 404

### ISSUE THREAD

**Issue by skazhy** [jafingerhut/clojure-cheatsheets#30]
`/` gets escaped when creating the method slug and creates the following url: http://clojuredocs.org/clojure.core/_ (which is 404).

Correct url for this method is: http://clojuredocs.org/clojure.core/_fs

**Comment by jafingerhut** [comment]
Thanks for filing the issue.  Should be fixed now, everywhere except on http://clojure.org/cheatsheet - That one might wait to get fixed for a while, since it was just updated, and I'd prefer not to bother them for fixing very tiny things.  Hopefully Clojure 1.7 release won't be too many months away, and that should be a good reason to update the cheat sheet there.
