### ISSUE TITLE
clojure.core/update missing

### ISSUE THREAD

**Issue by cloojure** [jafingerhut/clojure-cheatsheets#42]
Hi,

I love the cheatsheets, but noticed that clojure.core/update is missing on this page:

http://jafingerhut.github.io/cheatsheet/clojuredocs/cheatsheet-tiptip-cdocs-summary.html

I couldn't add a "see also" entry, and I get a 404 if I click on "update" in the vector section.

Alan

**Comment by jafingerhut** [comment]
Most of the links on that version of the cheat sheet go to the web site ClojureDocs.org, which has not yet been updated for Clojure 1.7.0.  Sorry for my part in causing confusion here, since I've released a version of the cheat sheet with these links that don't go anywhere yet, but if you want those links to go somewhere useful, the only way that will happen is if the people who maintain the ClojureDocs.org web site update it to add the things new in Clojure 1.7.0.  They might prefer to do that after Clojure 1.7.0 has been officially released.

There is an issue requesting this update to the ClojureDocs.org web site here: https://github.com/zk/clojuredocs/issues/110 that you can add your request to, if you like.

**Comment by jafingerhut** [comment]
clojure.core/update was added to ClojureDocs.org some time ago, I think.  Closing this issue now.
